# Generated by Django 2.1.7 on 2019-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bringpdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=999, verbose_name='分类排序'),
        ),
    ]
