# Generated by Django 2.1.7 on 2019-03-11 09:31

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bringpdf', '0002_category_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='intro',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pdf_img/%Y/%m/%d/', verbose_name='PDF图片'),
        ),
    ]
