# Generated by Django 2.1.7 on 2019-03-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bringpdf', '0003_auto_20190311_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='get_code',
            field=models.CharField(default='', max_length=20, verbose_name='提取码'),
            preserve_default=False,
        ),
    ]
